---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: backendappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: backend
 template:
  metadata:
   name: backend
   labels:
     app: backend
  spec:
    containers:
    - name: backendcontainer
      image: backend_app
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: backendsvc
spec:
  type: NodePort
  selector:
   app: backend
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30001
...