name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Frontend
      run: |
        cd ../../client
        docker-compose -f deployment.yml up -d
      env:
        DOCKER_COMPOSE_VERSION: 3

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Backend
      run: |
        cd ../../server
        docker-compose -f deployment.yml up -d
      env:
        DOCKER_COMPOSE_VERSION: 3
