name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1
            
      with:
        dockerfile: ./jenkins/Dockerfile

    - name: Build and push Jenkins image
      run: |
        docker build -t chayma701/jenkins:latest ./jenkins
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push chayma701/jenkins:latest

    - name: Run Jenkins pipeline
      run: |
        docker run -v /var/run/docker.sock:/var/run/docker.sock \
                   -v $(pwd):/workspace \
                   -e BUILD_NUMBER=$GITHUB_RUN_NUMBER \
                   chayma701/jenkins:latest
      env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
